SELECT [COFI_CORP_CODE]
      ,[COFI_PART_NO]
      ,[COFI_EONO]
      ,[COFI_CUMT_NO]
      ,[COFI_MATL_STND]
      ,[COFI_MATL_CODE]
      ,[COFI_MATL_APDT]
      ,[COFI_MATL_IMSI]
      ,[COFI_MATL_NAME]
      ,[COFI_MATL_UNIT]
      ,[COFI_MATL_GUBN]
      ,[COFI_IMPT_CODE]
      ,[COFI_MATL_GBCD]
      ,[COFI_MATT_KIND]
      ,[COFI_PROC_GUBN]
      ,[COFI_PROC_NUM0]
      ,[COFI_FORG_CODE]
      ,[COFI_CHIP_STND]
      ,[COFI_CHIP_CODE]
      ,[COFI_CHIP_APDT]
      ,[COFI_CHIP_IMSI]
      ,[COFI_CUTT_YN]
      ,[COFI_CUTT_REMK]
      ,[COFI_UPDT_CMAN]
      ,[COFI_UPDT_DATE]
      ,[COFI_INIT_CMAN]
      ,[COFI_INIT_DATE]
  FROM [TEST].[KPTD191].[RMSFLE].[PFRACOFI]
WHERE  COFI_CORP_CODE = 'K001'
AND    COFI_EONO      = 'E01'
AND    COFI_CUMT_NO   = '1127132'
GO


SELECT 
       [COFI_PROC_GUBN]
      ,[COFI_PROC_NUM0]
      ,[COFI_FORG_CODE]
  FROM [TEST].[KPTD191].[RMSFLE].[PFRACOFI]
WHERE  COFI_CORP_CODE = 'K001'
AND    COFI_EONO      = 'E01'
AND    COFI_CUMT_NO   = '1127132'



